In [1]:
import numpy

In [2]:
import tensorflow as tf
print(tf.version)

2022-07-20 14:30:03.829862: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-07-20 14:30:03.829975: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.


<module 'tensorflow._api.v2.version' from '/home/erichu/.local/lib/python3.10/site-packages/tensorflow/_api/v2/version/__init__.py'>


In [3]:
# rank: number of dimensions of a tensor
rank1_tensor = tf.Variable(["Test", "Ok", "Tim"], tf.string)
rank2_tensor = tf.Variable([["kekw", "kekw2"], ["lul", "lul2"]], tf.string)
tf.rank(rank1_tensor)
tf.rank(rank2_tensor)

2022-07-20 14:30:16.094269: E tensorflow/stream_executor/cuda/cuda_driver.cc:271] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
2022-07-20 14:30:16.094331: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (fedora): /proc/driver/nvidia/version does not exist
2022-07-20 14:30:16.094902: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [4]:
# shape: amount of elements that exist in each dimension
rank2_tensor.shape

TensorShape([2, 2])

In [5]:
# changing shape
tensor1 = tf.ones([1,2,3])
# print(tensor1)
tensor2 = tf.reshape(tensor1, [2,3,1])
tensor3 = tf.reshape(tensor2, [3, -1]) # -1: infers what shape the tensor should be

In [6]:
print(tensor1)
print(tensor2)
print(tensor3)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)
tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


In [7]:
# types of tensors:
# Variable, Constant, Placeholder, SparseTensor